version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/phpfpm/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/openresty/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
