#!/command/with-contenv bash

if [ ! "$ROLE" == "CRON" ] && [ ! "$ROLE" == "WORKER" ]; then
  exec /usr/sbin/php-fpm${PHP_VERSION} -F --fpm-config /etc/php/${PHP_VERSION}/fpm/php-fpm.conf
else
  # Not an FPM role (CRON/WORKER); park so s6 doesn't restart-loop this longrun.
  exec sleep infinity
fi
