#!/usr/bin/with-contenv bash

# TODO: Disabled April 2023 since we're not currently using PHP metrics anywhere and there's a golang CVE.

#if [ ! "$ROLE" == "CRON" ] || [ ! "$ROLE" == "WORKER" ]; then
#  /usr/local/bin/php-fpm_exporter server --phpfpm.fix-process-count --phpfpm.scrape-uri=tcp://127.0.0.1:9000/status
#fi
