#!/command/with-contenv bash

if [ "$ROLE" == "CRON" ] || [ "$ROLE" == "WORKER" ] || [ "$ROLE" == "MONOLITHIC" ]; then
   /usr/local/bin/supercronic -overlapping -split-logs /nhsla/cron 1>/dev/stdout
fi