name: Build Openresty Image

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 1 * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nhsl-ubuntu-phpv2
  ORG: nhsleadership

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cleanup PHP modules
        run: |
          echo php72mods=$(tr -d '\r' < ./phpfpm/php72.txt) >> $GITHUB_ENV && \
          echo php73mods=$(tr -d '\r' < ./phpfpm/php73.txt)" >> $GITHUB_ENV && \
          echo php74mods=$(tr -d '\r' < ./phpfpm/php74.txt)" >> $GITHUB_ENV && \
          echo php80mods=$(tr -d '\r' < ./phpfpm/php80.txt)" >> $GITHUB_ENV && \
          echo php81mods=$(tr -d '\r' < ./phpfpm/php81.txt)" >> $GITHUB_ENV
      
      - name: cat php72 mods
        run: |
          cat ./phpfpm/php72.txt
        id: php72mods

      - name: Login to GHCR
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Enumerate PHP modules
        run: |
          eeee
        id: 72mods

      - name: Build and push PHP 7.2
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./phpfpm
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }}:7.2-master
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=7.2
            PHP_PACKAGES=${{ env.php72mods }}

      - name: Build and push PHP 7.3
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./phpfpm
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }}:7.3-master
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=7.3
            PHP_PACKAGES=${{ env.php73mods }}

      - name: Build and push PHP 7.4
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./phpfpm
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }}:7.4-master
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=7.4
            PHP_PACKAGES=${{ env.php74mods }}

      - name: Build and push PHP 8.0
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./phpfpm
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }}:8.0-master
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=8.0
            PHP_PACKAGES=${{ env.php80mods }}

      - name: Build and push PHP 8.1
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./phpfpm
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }}:8.1-master
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=8.1
            PHP_PACKAGES=${{ env.php81mods }}

